export type { LoginLang as EmployeeLang } from '@/lib/login-tr'
import type { LoginLang } from '@/lib/login-tr'

type Lang = LoginLang

const TR = {
  th: {
    'nav.section':      'Menu',
    'nav.home':         'หน้าหลัก',
    'nav.assessment':   'แบบประเมิน',
    'nav.profile':      'โปรไฟล์ PERFORM-6™',
    'nav.activities':   'กิจกรรม',
    'nav.credits':      'กระเป๋าเครดิต',
    'nav.bookings':     'การจองของฉัน',
    'nav.feedback':     'ความคิดเห็น',
    'nav.help':         'ศูนย์ช่วยเหลือ',
    'page.home':        'My Performia',
    'page.assessment':  'แบบประเมิน',
    'page.profile':     'โปรไฟล์ PERFORM-6™',
    'page.marketplace': 'กิจกรรม',
    'search.ph':        'ค้นหากิจกรรม...',
    // Hero
    'hero.greeting':    'สวัสดี คุณ',
    'hero.sub':         'วันนี้คุณอยากดูแลตัวเองด้านไหน',
    'hero.cta1':        'ดูกิจกรรมที่เหมาะกับฉัน',
    'hero.cta2':        'ดูโปรไฟล์ของฉัน',
    'hero.credits.lbl': 'เครดิตคงเหลือ',
    'hero.bookings.lbl':'กิจกรรมที่จอง',
    'hero.bookings.unit':'รายการ',
    // Pillar short labels (strip)
    'pillar.mind':      'ใจ',
    'pillar.body':      'กาย',
    'pillar.social':    'สังคม',
    'pillar.growth':    'การเติบโต',
    'pillar.work':      'การทำงาน',
    'pillar.money':     'การเงิน',
    // CreditSummaryCard
    'credit.title':     'เครดิตคงเหลือ',
    'credit.fy':        'ปีงบประมาณ',
    'credit.chip':      'Active',
    'credit.rem':       'คงเหลือ',
    'credit.used':      'ใช้ไปแล้ว',
    'credit.total':     'ทั้งหมด',
    'credit.micro':     'ใช้เครดิตของคุณกับกิจกรรมที่ช่วยดูแลตัวเองได้ตลอดปี',
    'credit.cta':       'ใช้เครดิตกับกิจกรรม',
    // WellbeingSnapshot
    'snap.title':       'ภาพรวมของคุณ',
    'snap.sub':         'PERFORM-6™ Wellbeing Snapshot',
    'snap.link':        'ดูโปรไฟล์เต็ม →',
    'snap.footer':      'ดูรายละเอียดโปรไฟล์ทั้ง 6 มิติของคุณ',
    'snap.cta':         'ดูโปรไฟล์ PERFORM-6™',
    // RecommendedFocus
    'focus.title':      'เสาที่แนะนำสำหรับคุณเดือนนี้',
    'focus.sub':        'จากโปรไฟล์ PERFORM-6™ ของคุณ',
    'focus.link':       'ดูทั้งหมด →',
    'focus.cta':        'ดูกิจกรรม',
    'focus.unit':       'กิจกรรม',
    // QuickActions
    'quick.title':      'ทางลัด',
    'quick.profile':    'โปรไฟล์ของฉัน',
    'quick.credits':    'เครดิตของฉัน',
    'quick.activities': 'กิจกรรมของฉัน',
    'quick.assessment': 'แบบประเมิน',
    'quick.help':       'ศูนย์ช่วยเหลือ',
    // ActivitiesCarousel
    'act.title':        'กิจกรรมที่เหมาะกับคุณ',
    'act.sub':          'คัดสรรพิเศษจากโปรไฟล์ PERFORM-6™ ของคุณ',
    'act.link':         'ดูทั้งหมด →',
    'act.cta':          'ดูรายละเอียด',
    // BookingsSection
    'book.title':       'กิจกรรมที่กำลังจะเข้าร่วม',
    'book.sub':         'การจองที่ยืนยันแล้วของคุณ',
    'book.link':        'จัดการทั้งหมด →',
    'book.status':      'ยืนยันแล้ว',
    'book.manage':      'จัดการ',
    // Assessment
    'assess.saved':                 'บันทึกแล้ว',
    'assess.intro.title':           'แบบประเมิน PERFORM-6™',
    'assess.intro.sub':             'ตอบคำถามเพื่อรับโปรไฟล์สุขภาพส่วนตัวและคำแนะนำกิจกรรมที่เหมาะกับคุณ',
    'assess.intro.stat.q':          '36',
    'assess.intro.stat.q.lbl':      'คำถาม',
    'assess.intro.stat.t':          '6–8 นาที',
    'assess.intro.stat.t.lbl':      'เวลาโดยประมาณ',
    'assess.intro.cta':             'เริ่มทำแบบประเมิน',
    'assess.priv.title':            'ความเป็นส่วนตัวของคุณ',
    'assess.priv.body':             'ข้อมูลของคุณได้รับการคุ้มครองอย่างเต็มที่ ระบบออกแบบเพื่อช่วยเหลือคุณเท่านั้น',
    'assess.priv.pt1':              'HR เห็นเฉพาะข้อมูลภาพรวมของทีม ไม่เห็นคำตอบรายบุคคล',
    'assess.priv.pt2':              'ผลลัพธ์เป็นของคุณส่วนตัว ใช้เพื่อแนะนำกิจกรรมที่เหมาะกับคุณ',
    'assess.priv.pt3':              'คุณสามารถหยุดและบันทึกความคืบหน้าได้ทุกเมื่อ',
    'assess.priv.cta':              'รับทราบ เริ่มทำแบบประเมิน',
    'assess.priv.back':             'ย้อนกลับ',
    'assess.priv.inline':           'HR เห็นเฉพาะข้อมูลภาพรวม ไม่เห็นคำตอบรายบุคคล',
    'assess.pillar.Mind':           'จิตใจ',
    'assess.pillar.Body':           'ร่างกาย',
    'assess.pillar.Money':          'การเงิน',
    'assess.pillar.Social':         'สังคม',
    'assess.pillar.Growth':         'การเติบโต',
    'assess.pillar.WorkDesign':     'การออกแบบงาน',
    'assess.q.label':               '{pillar} · คำถาม {n}/{total}',
    'assess.scale.likert':          '1 = แทบไม่เคย · 5 = เกือบเสมอ',
    'assess.scale.situation':       'เลือกสถานการณ์ที่ตรงกับคุณมากที่สุด',
    'assess.likert.1':              '1 – แทบไม่เคย',
    'assess.likert.2':              '2 – นานๆ ครั้ง',
    'assess.likert.3':              '3 – บางครั้ง',
    'assess.likert.4':              '4 – บ่อยครั้ง',
    'assess.likert.5':              '5 – เกือบเสมอ',
    'assess.val.required':          'กรุณาเลือกคำตอบก่อนดำเนินการต่อ',
    'assess.btn.back':              'ย้อนกลับ',
    'assess.btn.save_exit':         'บันทึกและออก',
    'assess.btn.next':              'ถัดไป',
    'assess.btn.submit':            'ส่งคำตอบ',
    'assess.btn.submitting':        'กำลังส่ง…',
    'assess.btn.view_profile':      'ดูโปรไฟล์ของฉัน',
    'assess.btn.view_activities':   'ดูกิจกรรมแนะนำ',
    'assess.alert.saved':           'บันทึกความคืบหน้าแล้ว คุณสามารถกลับมาทำต่อได้',
    'assess.progress.q_of':         'คำถาม {c} / {t}',
    'assess.progress.pct':          '{p}%',
    'assess.time.plural':           'ประมาณ {n} นาที',
    'assess.time.one':              'น้อยกว่า 1 นาที',
    'assess.res.title':             'สรุปผล PERFORM-6™ ของคุณ',
    'assess.res.sub':               'นี่คือภาพรวมสุขภาพส่วนตัว เพื่อช่วยให้คุณเลือกการดูแลที่เหมาะกับตัวเอง',
    'assess.res.overall':           'Human Performance Score',
    'assess.res.sec.persona':       'บุคลิกภาพด้านสุขภาพของคุณ',
    'assess.res.sec.pillars':       'คะแนนแต่ละด้าน PERFORM-6™',
    'assess.res.sec.strengths':     'จุดแข็งของคุณ',
    'assess.res.sec.support':       'ด้านที่แนะนำให้ดูแลเพิ่มเติม',
    'assess.res.sec.activities':    'กิจกรรมที่เหมาะกับคุณ',
    'assess.res.privacy':           'ผลลัพธ์นี้เป็นข้อมูลส่วนตัวของคุณ HR จะเห็นเฉพาะข้อมูลภาพรวม ไม่เห็นคำตอบรายบุคคล',
    'assess.act.book':              'จอง',
    'assess.act.credits':           '{n} เครดิต',
    'assess.zone.performing.name':  'Performing Zone',
    'assess.zone.stable.name':      'Stable Zone',
    'assess.zone.watch.name':       'Watch Zone',
    'assess.zone.risk.name':        'Risk Zone',
    'assess.zone.critical.name':    'Critical Zone',
    'assess.zone.performing.label': 'แข็งแรงและพร้อมเติบโต',
    'assess.zone.stable.label':     'โดยรวมดี ควรดูแลต่อเนื่อง',
    'assess.zone.watch.label':      'ควรดูแลเพิ่มเติม',
    'assess.zone.risk.label':       'ควรได้รับการดูแลอย่างเหมาะสม',
    'assess.zone.critical.label':   'ควรได้รับการดูแลอย่างใกล้ชิด',
  },
  en: {
    'nav.section':      'Menu',
    'nav.home':         'Home',
    'nav.assessment':   'Assessment',
    'nav.profile':      'My PERFORM-6™ Profile',
    'nav.activities':   'Activities',
    'nav.credits':      'Credit Wallet',
    'nav.bookings':     'My Bookings',
    'nav.feedback':     'Feedback',
    'nav.help':         'Help Center',
    'page.home':        'My Performia',
    'page.assessment':  'Assessment',
    'page.profile':     'PERFORM-6™ Profile',
    'page.marketplace': 'Activities',
    'search.ph':        'Search activities...',
    // Hero
    'hero.greeting':    'Hello, ',
    'hero.sub':         'What would you like to take care of today?',
    'hero.cta1':        'View Recommended Activities',
    'hero.cta2':        'View My Profile',
    'hero.credits.lbl': 'Credits Remaining',
    'hero.bookings.lbl':'Upcoming Bookings',
    'hero.bookings.unit':'activities',
    // Pillar short labels (strip)
    'pillar.mind':      'Mind',
    'pillar.body':      'Body',
    'pillar.social':    'Social',
    'pillar.growth':    'Growth',
    'pillar.work':      'Work',
    'pillar.money':     'Money',
    // CreditSummaryCard
    'credit.title':     'Credits Remaining',
    'credit.fy':        'FY',
    'credit.chip':      'Active',
    'credit.rem':       'Remaining',
    'credit.used':      'Used',
    'credit.total':     'Total',
    'credit.micro':     'Use your credits throughout the year for activities that support your wellbeing.',
    'credit.cta':       'Use Credits for Activities',
    // WellbeingSnapshot
    'snap.title':       'Your Wellbeing Snapshot',
    'snap.sub':         'PERFORM-6™ Wellbeing Snapshot',
    'snap.link':        'View Full Profile →',
    'snap.footer':      'View all 6 dimensions of your wellbeing profile.',
    'snap.cta':         'View PERFORM-6™ Profile',
    // RecommendedFocus
    'focus.title':      'Recommended Focus This Month',
    'focus.sub':        'Based on your PERFORM-6™ profile',
    'focus.link':       'View All →',
    'focus.cta':        'View Activities',
    'focus.unit':       'activities',
    // QuickActions
    'quick.title':      'Quick Actions',
    'quick.profile':    'My Profile',
    'quick.credits':    'My Credits',
    'quick.activities': 'My Activities',
    'quick.assessment': 'Assessment',
    'quick.help':       'Help Center',
    // ActivitiesCarousel
    'act.title':        'Recommended Activities',
    'act.sub':          'Curated from your PERFORM-6™ profile',
    'act.link':         'View All →',
    'act.cta':          'View Details',
    // BookingsSection
    'book.title':       'Upcoming Activities',
    'book.sub':         'Your confirmed bookings',
    'book.link':        'Manage All →',
    'book.status':      'Confirmed',
    'book.manage':      'Manage',
    // Assessment
    'assess.saved':                 'Saved',
    'assess.intro.title':           'PERFORM-6™ Assessment',
    'assess.intro.sub':             'Answer a few questions to receive your personal wellbeing profile and activity recommendations.',
    'assess.intro.stat.q':          '36',
    'assess.intro.stat.q.lbl':      'Questions',
    'assess.intro.stat.t':          '6–8 min',
    'assess.intro.stat.t.lbl':      'Estimated time',
    'assess.intro.cta':             'Start Assessment',
    'assess.priv.title':            'Your Privacy Matters',
    'assess.priv.body':             'Your data is fully protected. This system is designed to support you, not to evaluate you.',
    'assess.priv.pt1':              'HR sees only team-level aggregated insights, not your individual answers.',
    'assess.priv.pt2':              'Your results are personal — used only to recommend activities that support you.',
    'assess.priv.pt3':              'You can pause and save your progress at any time.',
    'assess.priv.cta':              'Understood — Start Assessment',
    'assess.priv.back':             'Back',
    'assess.priv.inline':           'HR sees aggregated insights only — not your individual answers.',
    'assess.pillar.Mind':           'Mind Resilience',
    'assess.pillar.Body':           'Energy Vitality',
    'assess.pillar.Money':          'Financial Confidence',
    'assess.pillar.Social':         'Social Connection',
    'assess.pillar.Growth':         'Growth Momentum',
    'assess.pillar.WorkDesign':     'WorkFlow Clarity',
    'assess.q.label':               '{pillar} · Q {n}/{total}',
    'assess.scale.likert':          '1 = Almost never · 5 = Almost always',
    'assess.scale.situation':       'Select the situation that best describes you.',
    'assess.likert.1':              '1 – Almost never',
    'assess.likert.2':              '2 – Rarely',
    'assess.likert.3':              '3 – Sometimes',
    'assess.likert.4':              '4 – Often',
    'assess.likert.5':              '5 – Almost always',
    'assess.val.required':          'Please select an answer to continue.',
    'assess.btn.back':              'Back',
    'assess.btn.save_exit':         'Save & Exit',
    'assess.btn.next':              'Next',
    'assess.btn.submit':            'Submit Assessment',
    'assess.btn.submitting':        'Submitting…',
    'assess.btn.view_profile':      'View My Profile',
    'assess.btn.view_activities':   'View Recommended Activities',
    'assess.alert.saved':           'Progress saved. You can return to finish later.',
    'assess.progress.q_of':         'Q {c} / {t}',
    'assess.progress.pct':          '{p}%',
    'assess.time.plural':           'About {n} min remaining',
    'assess.time.one':              'Less than 1 min remaining',
    'assess.res.title':             'Your PERFORM-6™ Result Summary',
    'assess.res.sub':               'A personal wellbeing snapshot to help you choose the right support.',
    'assess.res.overall':           'Human Performance Score',
    'assess.res.sec.persona':       'Your Wellbeing Persona',
    'assess.res.sec.pillars':       'PERFORM-6™ Pillar Scores',
    'assess.res.sec.strengths':     'Your Strengths',
    'assess.res.sec.support':       'Areas to Support',
    'assess.res.sec.activities':    'Recommended Activities for You',
    'assess.res.privacy':           'This profile is personal to you. HR sees aggregated insights only, not individual answers.',
    'assess.act.book':              'Book',
    'assess.act.credits':           '{n} Credits',
    'assess.zone.performing.name':  'Performing Zone',
    'assess.zone.stable.name':      'Stable Zone',
    'assess.zone.watch.name':       'Watch Zone',
    'assess.zone.risk.name':        'Risk Zone',
    'assess.zone.critical.name':    'Critical Zone',
    'assess.zone.performing.label': 'Strong and Ready to Grow',
    'assess.zone.stable.label':     'Stable with Room to Support',
    'assess.zone.watch.label':      'Needs Additional Support',
    'assess.zone.risk.label':       'Support Recommended',
    'assess.zone.critical.label':   'Close Support Recommended',
  },
} as const

export type EmployeeTrKey = keyof typeof TR.en

export function et(lang: Lang, key: EmployeeTrKey): string {
  const map = TR[lang] as Record<string, string>
  return map[key] ?? (TR.en as Record<string, string>)[key] ?? key
}

const MONTH_TH = ['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม']
const MONTH_EN = ['January','February','March','April','May','June','July','August','September','October','November','December']

export function monthYear(lang: Lang): string {
  const d = new Date()
  const months = lang === 'th' ? MONTH_TH : MONTH_EN
  return `${months[d.getMonth()]} ${d.getFullYear()}`
}
