export type LoginLang = 'th' | 'en'

const TR = {
  th: {
    'brand.tagline':        'Human Performance OS',
    'brand.badge':          'Enterprise Human Performance',
    'brand.headline':       'ยินดีต้อนรับสู่ Performia',
    'brand.supporting':     'เปลี่ยนความเป็นอยู่ที่ดีให้เป็นผลลัพธ์ที่วัดได้',
    'brand.copyright':      '© 2568 Performia. Human Performance Intelligence Platform.',
    'login.headline':       'ยินดีต้อนรับสู่ Performia',
    'login.subheadline':    'เข้าสู่ระบบเพื่อใช้งานแพลตฟอร์มของคุณ',
    'form.emailLabel':      'อีเมลองค์กร',
    'form.emailPlaceholder':'you@organization.com',
    'form.passwordLabel':   'รหัสผ่าน',
    'form.forgotPassword':  'ลืมรหัสผ่าน?',
    'form.rememberMe':      'จดจำการเข้าสู่ระบบ',
    'form.signIn':          'เข้าสู่ระบบ',
    'form.orWith':          'หรือเข้าสู่ระบบด้วย',
    'form.privacy':         'ข้อมูลส่วนบุคคลของคุณได้รับการดูแลอย่างปลอดภัย โดย HR จะเห็นเฉพาะข้อมูลภาพรวม ไม่สามารถเห็นคำตอบรายบุคคลได้',
    'val.noEmail':          'กรุณากรอกอีเมลองค์กรของคุณ',
    'val.invalidEmail':     'กรุณากรอกอีเมลที่ถูกต้อง',
    'val.noPassword':       'กรุณากรอกรหัสผ่าน',
    'val.ssoConnect':       'กำลังเชื่อมต่อกับ',
    'footer.privacy':       'นโยบายความเป็นส่วนตัว',
    'footer.terms':         'เงื่อนไขการใช้งาน',
    'footer.support':       'ติดต่อฝ่ายสนับสนุน',
    'ws.title':             'เลือกพื้นที่ทำงาน',
    'ws.subtitle':          'คุณมีสิทธิ์เข้าถึงหลายพื้นที่ทำงาน',
    'ws.employee.title':    'My Performia',
    'ws.employee.desc':     'โปรไฟล์สุขภาวะ เครดิต และกิจกรรมโปรแกรมของคุณ',
    'ws.hr.title':          'แดชบอร์ด HR & People',
    'ws.hr.desc':           'การมีส่วนร่วม การวิเคราะห์กำลังคน และการจัดการงบประมาณ',
    'ws.exec.title':        'Executive Intelligence',
    'ws.exec.desc':         'ผลกระทบทางธุรกิจ ผลลัพธ์ ESG และรายงานเชิงกลยุทธ์',
    'redirect.to':          'กำลังนำทางไปยัง',
  },
  en: {
    'brand.tagline':        'Human Performance OS',
    'brand.badge':          'Enterprise Human Performance',
    'brand.headline':       'Welcome to Performia',
    'brand.supporting':     'Turn wellbeing into measurable performance.',
    'brand.copyright':      '© 2025 Performia. Human Performance Intelligence Platform.',
    'login.headline':       'Welcome to Performia',
    'login.subheadline':    'Sign in to continue to your workspace.',
    'form.emailLabel':      'Work Email',
    'form.emailPlaceholder':'you@organization.com',
    'form.passwordLabel':   'Password',
    'form.forgotPassword':  'Forgot password?',
    'form.rememberMe':      'Keep me signed in',
    'form.signIn':          'Sign in',
    'form.orWith':          'or continue with',
    'form.privacy':         'Your personal data is handled securely. HR sees aggregated insights only, not individual answers.',
    'val.noEmail':          'Please enter your work email.',
    'val.invalidEmail':     'Please enter a valid email address.',
    'val.noPassword':       'Please enter your password.',
    'val.ssoConnect':       'Connecting to',
    'footer.privacy':       'Privacy Policy',
    'footer.terms':         'Terms',
    'footer.support':       'Contact Support',
    'ws.title':             'Select Workspace',
    'ws.subtitle':          'You have access to multiple workspaces.',
    'ws.employee.title':    'My Performia',
    'ws.employee.desc':     'Your wellbeing profile, credits, and programme activities',
    'ws.hr.title':          'HR & People Dashboard',
    'ws.hr.desc':           'Participation, workforce analytics, and budget oversight',
    'ws.exec.title':        'Executive Intelligence',
    'ws.exec.desc':         'Business impact, ESG outcomes, and strategic reporting',
    'redirect.to':          'Redirecting you to',
  },
} as const

export type LoginTrKey = keyof typeof TR.en

export function tr(lang: LoginLang, key: LoginTrKey): string {
  const map = TR[lang] as Record<string, string>
  return map[key] ?? (TR.en as Record<string, string>)[key] ?? key
}
